### ISSUE TITLE
Credentails exposed

### ISSUE THREAD

**Issue by csquared** [sona3Admin/sona3-dev#3]
https://github.com/sona3Admin/sona3-dev/blob/8c71b1e25a2fa28fb11eb6a3c17d224ed7aef237/.env#L1-L4

This would be the 3rd time in three days. Your Bucketeer account has been suspended at the moment - please open a support ticket so we can get an acknolwedgement that they keys cannot be public or you might have your data deleted or account otherwise compromised. Apologies for the inconvenience.

**Comment by sona3Admin** [comment]
Sorry, I will remove the credentials from the .env file and redeploy the app, 
but if I put the credentials in the config var section in settings tab, would the credentials still be public in this case too?
