### ISSUE TITLE
Credentials exposed

### ISSUE THREAD

**Issue by csquared** [sona3Admin/sona3-dev#4]
https://github.com/sona3Admin/sona3-dev/blob/3c99bbd63644169f0238a78c7a3a5f57914c6fdd/.env#L1C29-L4

Hey Guys:
It happened again. You should not have the `.env` file committed to your repo. I've deleted these keys - you can log in to your web UI and use "roll key" to issue new ones. If those new ones wind up on github again I will have to disable the button until you're able to figure this out.
Cheers,
Chris

**Comment by sona3Admin** [comment]
Hi Chris, sorry for the inconvenience and thanks for your patience.
The .env file is no longer pushed to github and the credentials are securely stored as config vars in the settings tab.
